[versions]
kotlin = "2.3.21"
femtojar = "0.1.6"
junit = "6.1.1"
assertj = "3.27.7"
gradle-maven-publish-plugin = "0.37.0"

[libraries]
femtojar-core = { group = "me.bechberger", name = "femtojar", version.ref = "femtojar" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish-plugin" }
